name: Test Drone Program 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python test_drone_program.py
          python3 -m unittest Test_DroneProgram.py
          python3 -m unittest Test_FlaskThrottle.py
          python3 -m unittest Test_FlaskAileron.py
          python3 -m unittest Test_FlaskElevator.py
          python3 -m unittest Test_FlaskRudder.py
